apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/version: "0.1.0-alpha"
  name: workshop-config
  namespace: drone
data:
  workshop.yaml: |-
      giteaAdminUserName: demo
      giteaAdminUserPassword: demo@123
      giteaURL: http://gitea-http.default:30950/
      users:
        from: 1
        to: 1
        oAuthAppName: demo-oauth
        oAuthRedirectURI: ${DRONE_SERVER_URL}
        addKubernetesSecret: true
        secretNamespace: drone
        repos:
          - https://github.com/harness-apps/dag-stack.git
          - https://github.com/harness-apps/dag-setup-verifier.git
          - https://github.com/harness-apps/quarkus-springboot-demo.git
          - https://github.com/harness-apps/quarkus-springboot-demo-gitops.git
